name: Pull Request Checks

# Run this workflow every time a new pull request is opened
# and when commits are pushed to an existing PR
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  # Set the job key. This key is displayed as the job name
  # when a job name is not provided
  pr-checks:
    env:
      working-directory: ./client
    name: Pull Request Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        working-directory: ${{env.working-directory}}
        run: yarn install --frozen-lockfile

      # Runs actions specific script that does not fix errors
      - name: Check linting
        working-directory: ${{env.working-directory}}
        run: yarn run lint-ci

      # Runs all jest tests
      - name: Check Jest tests
        working-directory: ${{env.working-directory}}
        run: yarn run test-ci

      # Run all Cypress tests in Chrome
      - name: Check Cypress tests
        uses: cypress-io/github-action@v2
        with:
            browser: chrome
            start: yarn start
            working-directory: ${{env.working-directory}}

      # Ensure that their are no errors in the build
      - name: Check build
        working-directory: ${{env.working-directory}}
        run: yarn build